(* ::Package:: *)

(* Autogenerated Package *)

ASTObject::usage="An object representing an AST";


Begin["`Private`"];


RegisterInterface[
  ASTObject,
  {"Tree"},
  "Constructor"->ConstructASTObject,
  "AccessorFunctions"->
    <|
      "Keys"->getKey, 
      "Parts"->GetASTNode
      |>
  ]


getKey[ASTObject[a_], k_]:=a[k]


End[];



