(* ::Package:: *)

(* Autogenerated Package *)

EBNFGrammar::usage=
  "An object defining an EBNFGrammar that we can use to build our Parser";


Begin["`Private`"];


(* ::Subsection:: *)
(*EBNFGrammar*)



RegisterInterface[
  EBNFGrammar,
  {
    "Rules"
    },
  "Constructor"->BuildEBNFGrammar
  ]


InterfaceMethod[EBNFGrammar]@
  g_EBNFGrammar["Lexer"][]:=BuildEBNFLexer[g];


InterfaceMethod[EBNFGrammar]@
  g_EBNFGrammar["Parser"][]:=BuildEBNFParser[g];


End[];



