(* ::Package:: *)

(* Autogenerated Package *)

LexerObject::usage="An object for lexing a stream";


Begin["`Private`"];


RegisterInterface[
  LexerObject,
  {"Tokens"},
  "Constructor"->ConstructLexerObject
  ]


(* ::Subsubsection::Closed:: *)
(*Methods*)



InterfaceMethod[LexerObject]@
  l_LexerObject["TokenStream"][stream_]:=
    TokenStream[l, stream];
InterfaceMethod[LexerObject]@
  l_LexerObject["Read"][stream_, n:_Integer?Positive:1]:=
    With[{ts=TokenStream[l, stream]},
      Internal`WithLocalSettings["",
        ts@"Read"[n],
        If[StringQ@stream, ts@"Close"[]]
        ]
      ]


End[];



