(* ::Package:: *)

(* Autogenerated Package *)

ParserObject::usage="An object for parsing a lexed stream";


Begin["`Private`"];


RegisterInterface[
  ParserObject,
  {"Lexer", "Handlers"},
  "Constructor"->ConstructParserObject
  ]


(* ::Subsubsection::Closed:: *)
(*Methods*)



InterfaceMethod[ParserObject]@
  l_ParserObject["Parse"][stream_]:=
    ApplyParser[l, stream];


End[];



